In [4]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [5]:
'''
    Next Few Tabs are just simple feature engineering functions as shown by the Data Analysis Kernel
'''

'\n    Next Few Tabs are just simple feature engineering functions as shown by the Data Analysis Kernel\n'

In [6]:
def getTitle(value):
    if "Rev." in value:
        return 1
    elif "Col." in value:
        return 2
    elif "Mr." in value:
        return 3
    elif "Dr." in value:
        return 4
    elif "Master" in value:
        return 5
    elif "Miss" in value or "Mlle" in value:
        return 6
    elif "Mrs." in value or "Mme" in value:
        return 7
    else:
        return 0

In [7]:
def getAgeGroup(value):
    if value<=8:
        return 1
    if value>8 and value<=14:
        return 3
    if value >14 and value<=28:
        return 4
    if value >28 and value<=63:
        return 5
    if value >63:
        return 6

In [8]:
def getFareGroup(value):
    if value<=10:
        return 1
    if value>10 and value<=25:
        return 2
    if value >25 and value<=35:
        return 3
    if value >35 and value<=60:
        return 4
    if value >60 and value<=150:
        return 5
    if value > 150:
        return 6

In [9]:
'''
    Simply done to clean the appropriate data 
'''

'\n    Simply done to clean the appropriate data \n'

In [11]:
df=pd.read_csv(r'Raw_Data/train.csv')

In [12]:
df.index=df['PassengerId']
df.drop('PassengerId',axis=1,inplace=True)

In [13]:
df['male']=pd.get_dummies(df['Sex'])['male']

In [14]:
df['Q']=pd.get_dummies(df['Embarked'])['Q']
df['S']=pd.get_dummies(df['Embarked'])['S']

In [15]:
df['hasCabin']=df['Cabin'].apply(lambda x: 1 if type(x)==str else 0)

In [16]:
df=df[df['Age'].notnull()]

In [17]:
df['isChildRich']=0
df['isChildRich']=df['isChildRich'][df.Age<17][df.Pclass==1].replace(0,1)
df['isChildRich'].fillna(0,inplace=True)
df['isChildRich']=df['isChildRich'].apply(lambda x: int(x))

In [18]:
df['Age_Group']=df['Age'].apply(getAgeGroup)

In [19]:
df['Title']=df['Name'].apply(getTitle)

In [20]:
df['Fare_Group']=df['Fare'].apply(getFareGroup)

In [21]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

In [22]:
x=df[['Pclass','male','SibSp','Title','isChildRich','hasCabin','Age_Group','Fare_Group','Q','S']]
y=df['Survived']

In [23]:
from sklearn.model_selection import train_test_split

In [71]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=101)

In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [74]:
predictions=logmodel.predict(x_test)

In [75]:
from sklearn.metrics import classification_report,confusion_matrix

In [76]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.79      0.91      0.85       123
          1       0.85      0.67      0.75        92

avg / total       0.81      0.81      0.81       215



In [77]:
print(confusion_matrix(y_test,predictions))

[[112  11]
 [ 30  62]]


In [78]:
from sklearn.tree import DecisionTreeClassifier

In [79]:
dtree=DecisionTreeClassifier()

In [80]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [81]:
predictions_tree=dtree.predict(x_test)

In [82]:
print(classification_report(y_test,predictions_tree))

             precision    recall  f1-score   support

          0       0.75      0.87      0.81       123
          1       0.78      0.62      0.69        92

avg / total       0.77      0.76      0.76       215



In [83]:
print(confusion_matrix(y_test,predictions_tree))

[[107  16]
 [ 35  57]]


In [84]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
rfc=RandomForestClassifier(n_estimators=10000)

In [86]:
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [87]:
predictions_forrest=rfc.predict(x_test)

In [88]:
print(classification_report(y_test,predictions_forrest))

             precision    recall  f1-score   support

          0       0.82      0.88      0.85       123
          1       0.82      0.74      0.78        92

avg / total       0.82      0.82      0.82       215



In [89]:
print(confusion_matrix(y_test,predictions_forrest))

[[108  15]
 [ 24  68]]


In [90]:
from sklearn.svm import SVC

In [91]:
svc_model=SVC()

In [92]:
svc_model.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [93]:
predict_svc=svc_model.predict(x_test)

In [94]:
print(classification_report(y_test,predict_svc))

             precision    recall  f1-score   support

          0       0.79      0.93      0.85       123
          1       0.87      0.66      0.75        92

avg / total       0.82      0.81      0.81       215



In [95]:
from sklearn.model_selection import GridSearchCV

In [96]:
Cs = [0.001, 0.01, 0.1, 1, 10,100,1000]
gammas = [0.001, 0.01, 0.1, 1,10,100]

In [97]:
param_grid = {'C': Cs, 'gamma' : gammas}

In [98]:
grid=GridSearchCV(SVC(),param_grid,refit=True,verbose=2)

In [99]:
grid.fit(x_train,y_train)

Fitting 3 folds for each of 42 candidates, totalling 126 fits
[CV] C=0.001, gamma=0.001 ............................................
[CV] ............................. C=0.001, gamma=0.001, total=   0.0s
[CV] C=0.001, gamma=0.001 ............................................
[CV] ............................. C=0.001, gamma=0.001, total=   0.0s
[CV] C=0.001, gamma=0.001 ............................................
[CV] ............................. C=0.001, gamma=0.001, total=   0.0s
[CV] C=0.001, gamma=0.01 .............................................
[CV] .............................. C=0.001, gamma=0.01, total=   0.0s
[CV] C=0.001, gamma=0.01 .............................................
[CV] .............................. C=0.001, gamma=0.01, total=   0.0s
[CV] C=0.001, gamma=0.01 .............................................
[CV] .............................. C=0.001, gamma=0.01, total=   0.0s
[CV] C=0.001, gamma=0.1 ..............................................
[CV] ..........

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ............................... C=0.001, gamma=100, total=   0.0s
[CV] C=0.001, gamma=100 ..............................................
[CV] ............................... C=0.001, gamma=100, total=   0.0s
[CV] C=0.01, gamma=0.001 .............................................
[CV] .............................. C=0.01, gamma=0.001, total=   0.0s
[CV] C=0.01, gamma=0.001 .............................................
[CV] .............................. C=0.01, gamma=0.001, total=   0.0s
[CV] C=0.01, gamma=0.001 .............................................
[CV] .............................. C=0.01, gamma=0.001, total=   0.0s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   0.0s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   0.0s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] .

[CV] .................................. C=10, gamma=0.1, total=   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   0.0s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   0.0s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   0.0s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   0.0s
[CV] C=10, gamma=100 .................................................
[CV] .

[Parallel(n_jobs=1)]: Done 126 out of 126 | elapsed:    1.5s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000], 'gamma': [0.001, 0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=2)

In [100]:
grid_predict=grid.predict(x_test)

In [101]:
print(classification_report(y_test,grid_predict))

             precision    recall  f1-score   support

          0       0.77      0.94      0.85       123
          1       0.89      0.62      0.73        92

avg / total       0.82      0.80      0.80       215



In [102]:
print(confusion_matrix(y_test,grid_predict))

[[116   7]
 [ 35  57]]


In [103]:
data=pd.DataFrame(y_test)

In [104]:
data['Log']=list(predictions)
data['Tree']=list(predictions_tree)
data['Forrest']=list(predictions_forrest)
data['SVC']=list(predict_svc)
data['Grid']=list(grid_predict)

In [105]:
data.to_csv('Clean_Data/relearn.csv', encoding='utf-8', index=True)

In [106]:
#Test Data 

In [107]:
test_data=pd.read_csv(r'Clean_Data/test.csv')
test_data.index=test_data['PassengerId']
test_data.drop('PassengerId',axis=1,inplace=True)
test_data.loc[1044,'Fare']=20.00
test_data['male']=pd.get_dummies(test_data['Sex'])['male']
test_data['Q']=pd.get_dummies(test_data['Embarked'])['Q']
test_data['S']=pd.get_dummies(test_data['Embarked'])['S']
test_data['hasCabin']=test_data['Cabin'].apply(lambda x: 1 if type(x)==str else 0)
test_data['isChildRich']=0
test_data['isChildRich']=test_data['isChildRich'][test_data.Age<17][test_data.Pclass==1].replace(0,1)
test_data['isChildRich'].fillna(0,inplace=True)
test_data['isChildRich']=test_data['isChildRich'].apply(lambda x: int(x))
test_data['Age_Group']=test_data['Age'].apply(getAgeGroup)
test_data['Title']=test_data['Name'].apply(getTitle)
test_data['Fare_Group']=test_data['Fare'].apply(getFareGroup)
test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1
x_test_data=test_data[['Pclass','male','SibSp','Title','isChildRich','hasCabin','Age_Group','Fare_Group','Q','S']]

In [108]:
#Model Predictions

In [109]:
LOG=logmodel.predict(x_test_data)
TREE=dtree.predict(x_test_data)
FORR=rfc.predict(x_test_data)
SVC=svc_model.predict(x_test_data)
GRID=grid.predict(x_test_data)

In [110]:
data2=pd.DataFrame(index=x_test_data.index)
data2['Log']=list(LOG)
data2['Tree']=list(TREE)
data2['Forrest']=list(FORR)
data2['SVC']=list(SVC)
data2['Grid']=list(GRID)

In [111]:
data2.to_csv('Clean_Data/test_relearn.csv', encoding='utf-8', index=True)

In [112]:
#This was done to test cross-validation method versus using plain ML techniques
submission=pd.DataFrame(index=test_data.index)
submission['Survived']=list(GRID)
submission.to_csv('titanic_submission.csv', encoding='utf-8', index=True)